### PR TITLE
chore: bump Fedora version to 41

### PR DESCRIPTION
**Pull request by ryanabx**
Now that Fedora 41 is stable, we should update the cosmic image to use Fedora 41.

Also updated the neofetch image as the old one is, well, old :sweat_smile:

### CODE REVIEW

**Comment by p5** [comment]
We're probably almost ready to archive this repo, and move these images to ublue-os/main since Timothee's now pushing Cosmic images

**Review by p5 — DISMISSED** [review]

**Comment by ryanabx** [comment]
Good point. The only thing this image has different than timothee's images is that they follow the nightly builds of cosmic. The tagged releases are mostly fine to use though

**Comment by etrigan63** [comment]
Question: `neofetch` has been archived and no longer developed. Should you be using `fastfetch` instead?

**Comment by ryanabx** [comment]
> Question: neofetch has been archived and no longer developed. Should you be using fastfetch instead?

For the screenshot? I'm using fastfetch for that yeah

**Comment by castrojo** [comment]
Ok the last PR fixed this, builds are going again.

**Pull request closed without merging**
